# Generated by Django 4.0.3 on 2022-04-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songrater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist', models.CharField(max_length=255)),
                ('song', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
