# Generated by Django 4.0.3 on 2022-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songrater', '0002_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('artist', models.CharField(max_length=255)),
                ('song', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('rating', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
