# Generated by Django 4.0.2 on 2022-04-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songrater', '0003_rating_delete_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='song',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
