# Generated by Django 4.0.4 on 2022-04-14 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songrater', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetterRating',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('artist', models.CharField(max_length=255)),
                ('song', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('song', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
