# Generated by Django 4.0.4 on 2022-04-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songrater', '0006_betterrating_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='betterrating',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='betterrating',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
