# Generated by Django 4.0.4 on 2022-04-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songrater', '0007_betterrating_id_alter_betterrating_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.CharField(max_length=255),
        ),
    ]
